using System.Text.RegularExpressions;

namespace Aibysitter.Rules.PullRequests;

/// <summary>Line-level reading of added code: generated files, comment-only lines, string-literal positions.</summary>
public static partial class CodeText
{
    private const int HeaderLines = 10;

    /// <summary>
    /// "&lt;auto-generated" in the first 10 lines of the file, read from the diff (added or context lines)
    /// or from the head content when fetched.
    /// </summary>
    public static bool IsGenerated(ChangedFile file)
    {
        ArgumentNullException.ThrowIfNull(file);

        if (file.Lines.Any(l => l.NewLine is <= HeaderLines && l.Text.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase)))
        {
            return true;
        }

        return file.HeadContent is { } head
            && head.Split('\n').Take(HeaderLines).Any(l => l.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase));
    }

    /// <summary>The line holds only a comment: //, /*, *, #, --, &lt;!-- (not Rust #[...]).</summary>
    public static bool IsCommentOnly(string line) => CommentOnlyRegex().IsMatch(line);

    /// <summary>
    /// True when <paramref name="index"/> falls inside a string literal opened on this line: "…", '…', `…`,
    /// C# verbatim @"…" and raw """…""". A // comment (or # for hash-comment languages) ends the scan.
    /// Strings continued from earlier lines are not seen.
    /// </summary>
    public static bool IsInsideStringLiteral(string line, int index, bool hashComments = false)
    {
        ArgumentNullException.ThrowIfNull(line);

        char? quote = null;
        var verbatim = false;
        var rawLength = 0;
        for (var i = 0; i < index && i < line.Length; i++)
        {
            var c = line[i];
            if (quote is null)
            {
                if ((c == '/' && i + 1 < line.Length && line[i + 1] == '/') || (hashComments && c == '#'))
                {
                    return false;
                }

                if (c is not ('"' or '\'' or '`'))
                {
                    continue;
                }

                quote = c;
                var run = QuoteRun(line, i);
                if (c == '"' && run >= 3)
                {
                    rawLength = run;
                    i += run - 1;
                }
                else
                {
                    verbatim = c == '"' && i > 0 && (line[i - 1] == '@' || (line[i - 1] == '$' && i > 1 && line[i - 2] == '@'));
                }
            }
            else if (rawLength > 0)
            {
                var run = c == '"' ? QuoteRun(line, i) : 0;
                if (run >= rawLength)
                {
                    quote = null;
                    rawLength = 0;
                }

                i += Math.Max(run - 1, 0);
            }
            else if (!verbatim && c == '\\')
            {
                i++;
            }
            else if (c == quote)
            {
                if (verbatim && i + 1 < line.Length && line[i + 1] == '"')
                {
                    i++;
                    continue;
                }

                quote = null;
                verbatim = false;
            }
        }

        return quote is not null;
    }

    /// <summary>
    /// Line numbers (head side) that hold only a comment, or sit inside a /* */ block comment or a Python
    /// triple-quoted docstring. Read from the head content when fetched, otherwise from the diff's added and
    /// context lines (state resets at each gap between hunks).
    /// </summary>
    public static IReadOnlySet<int> CommentLines(ChangedFile file)
    {
        ArgumentNullException.ThrowIfNull(file);

        var lines = file.HeadContent is { } head
            ? head.Replace("\r\n", "\n").Split('\n').Select((text, i) => (Number: i + 1, Text: text))
            : file.Lines.Where(l => l.NewLine is not null).Select(l => (Number: l.NewLine!.Value, l.Text));
        var python = Path.GetExtension(file.Path).Equals(".py", StringComparison.OrdinalIgnoreCase);

        var result = new HashSet<int>();
        var inBlock = false;
        string? docstring = null;
        var previous = 0;
        foreach (var (number, text) in lines)
        {
            if (number != previous + 1)
            {
                inBlock = false;
                docstring = null;
            }

            previous = number;
            if (inBlock)
            {
                result.Add(number);
                inBlock = !text.Contains("*/", StringComparison.Ordinal);
                continue;
            }

            if (docstring is not null)
            {
                result.Add(number);
                if (text.Contains(docstring, StringComparison.Ordinal))
                {
                    docstring = null;
                }

                continue;
            }

            if (IsCommentOnly(text))
            {
                result.Add(number);
            }

            var open = text.LastIndexOf("/*", StringComparison.Ordinal);
            if (open >= 0 && text.IndexOf("*/", open, StringComparison.Ordinal) < 0 && !IsInsideStringLiteral(text, open))
            {
                inBlock = true;
                result.Add(number);
                continue;
            }

            var trimmed = text.TrimStart();
            if (python && (trimmed.StartsWith("\"\"\"", StringComparison.Ordinal) || trimmed.StartsWith("'''", StringComparison.Ordinal)))
            {
                var delimiter = trimmed[..3];
                result.Add(number);
                if (CountOf(trimmed, delimiter) == 1)
                {
                    docstring = delimiter;
                }
            }
        }

        return result;
    }

    /// <summary>Python, shell, PowerShell, Ruby: # starts a comment.</summary>
    public static bool UsesHashComments(string path) =>
        Path.GetExtension(path).ToLowerInvariant() is ".py" or ".sh" or ".ps1" or ".psm1" or ".rb";

    private static int CountOf(string text, string token)
    {
        var count = 0;
        for (var i = text.IndexOf(token, StringComparison.Ordinal); i >= 0; i = text.IndexOf(token, i + token.Length, StringComparison.Ordinal))
        {
            count++;
        }

        return count;
    }

    private static int QuoteRun(string line, int start)
    {
        var end = start;
        while (end < line.Length && line[end] == '"')
        {
            end++;
        }

        return end - start;
    }

    [GeneratedRegex(@"^\s*(?://|/\*|\*|#(?!\[)|--|<!--)")]
    private static partial Regex CommentOnlyRegex();
}
