using Aibysitter.Rules.PullRequests;
using static Aibysitter.Rules.Tests.PullRequests.PrTestData;

namespace Aibysitter.Rules.Tests.PullRequests;

public class CodeTextTests
{
    [Fact]
    public void Generated_HeaderInAddedLines() =>
        Assert.True(CodeText.IsGenerated(Added("Migrations/X.Designer.cs", "// <auto-generated />", "using System;")));

    [Fact]
    public void Generated_HeaderInHeadContentOnly() =>
        Assert.True(CodeText.IsGenerated(new ChangedFile("R.Designer.cs", FileChangeStatus.Modified, "@@ -40,1 +40,1 @@\n-a\n+b", HeadContent: "//------\n// <auto-generated>\n//------\n")));

    [Fact]
    public void NotGenerated_HeaderBelowLine10() =>
        Assert.False(CodeText.IsGenerated(Added("A.cs", [.. Enumerable.Repeat("x", 10), "// <auto-generated />"])));

    [Fact]
    public void NotGenerated_ModifiedWithoutHeaderInView() =>
        Assert.False(CodeText.IsGenerated(new ChangedFile("A.cs", FileChangeStatus.Modified, "@@ -40,1 +40,1 @@\n-a\n+b")));

    [Theory]
    [InlineData("/// Any ::UPPERCASE:: marker blocks publication.")]
    [InlineData("  // TODO_X later")]
    [InlineData(" * ::NAME:: in a block comment")]
    [InlineData("# YOUR_KEY in YAML")]
    [InlineData("-- REPLACE_ME in SQL")]
    [InlineData("<!-- <placeholder> -->")]
    public void CommentOnly(string line) => Assert.True(CodeText.IsCommentOnly(line));

    [Theory]
    [InlineData("var key = \"YOUR_KEY\"; // note")]
    [InlineData("#[allow(dead_code)]")]
    public void NotCommentOnly(string line) => Assert.False(CodeText.IsCommentOnly(line));

    [Theory]
    [InlineData("var s = \"Server=x;Password=abcd1234;\";", "Password", true)]
    [InlineData("Password = string.Empty;", "Password", false)]
    [InlineData("var s = \"a\" + Password;", "Password", false)]
    [InlineData("var s = @\"C:\\dir\"\" Password=abcd\";", "Password", true)]
    [InlineData("var s = \"\"\"Password=abcd\"\"\";", "Password", true)]
    [InlineData("var s = \"\"\"x\"\"\" + Password;", "Password", false)]
    [InlineData("var s = \"esc \\\" still Password=abcd\";", "Password", true)]
    [InlineData("await page.EvaluateAsync(\"t => { try { x(); } catch(e){} }\", theme);", "catch", true)]
    [InlineData("try { x(); } catch (Exception) { } // \"catch\"", "catch", false)]
    [InlineData("var c = 'x'; catch", "catch", false)]
    [InlineData("const s = `catch`;", "catch", true)]
    public void InsideStringLiteral(string line, string token, bool expected) =>
        Assert.Equal(expected, CodeText.IsInsideStringLiteral(line, line.IndexOf(token, StringComparison.Ordinal)));

    [Fact]
    public void HashComment_EndsScan() =>
        Assert.False(CodeText.IsInsideStringLiteral("# don't Password=abcd", 8, hashComments: true));
}
