using Aibysitter.Rules.PullRequests;
using static Aibysitter.Rules.Tests.PullRequests.PrTestData;

namespace Aibysitter.Rules.Tests.PullRequests;

/// <summary>False-positive shapes from dogfood 1, and the true positives next to them.</summary>
public class Dogfood1TuningTests
{
    private static List<PullRequestFinding> Run(IPullRequestCheck check, params ChangedFile[] files) => check.Evaluate(Context(files)).ToList();

    // Generated files

    [Fact]
    public void GeneratedFile_SkippedByContentChecks()
    {
        var file = Added("src/Data/Migrations/20260101_Init.Designer.cs",
            "// <auto-generated />",
            "#pragma warning disable 612, 618",
            "var x = \"YOUR_KEY\";",
            "try { M(); } catch { }",
            "Debug.WriteLine(x);");

        Assert.Empty(Run(new SuppressedDiagnostics(), file));
        Assert.Empty(Run(new PlaceholderIdentifiers(), file));
        Assert.Empty(Run(new SwallowedExceptions(), file));
        Assert.Empty(Run(new DebugLeftovers(), file));
    }

    [Fact]
    public void GeneratedFile_SecretsStillFlagged() =>
        Assert.Single(Run(new SecretsInDiff(), Added("Gen.cs", "// <auto-generated />", "var c = \"Server=db;Password=Hunter2Prod;\";")));

    [Fact]
    public void HandWrittenFile_PragmaStillFlagged() =>
        Assert.Single(Run(new SuppressedDiagnostics(), Added("src/A.cs", "#pragma warning disable CS8602")));

    // P001

    [Theory]
    [InlineData("/// Any ::UPPERCASE:: marker blocks publication.")]
    [InlineData("    [InlineData(\"::PLACEHOLDER::\")]")]
    [InlineData("    [Theory, InlineData(\"::LEGAL_NAME::\")]")]
    [InlineData("    [TestCase(\"YOUR_TOKEN\")]")]
    [InlineData("    [DataRow(\"REPLACE_ME\")]")]
    [InlineData("    // TODO_ORDER_ID once the API exists")]
    public void P001_CommentsAndTestData_NotFlagged(string line) =>
        Assert.Empty(Run(new PlaceholderIdentifiers(), Added("src/Legal/Parser.cs", line)));

    [Theory]
    [InlineData("var name = \"::LEGAL_NAME::\";")]
    [InlineData("var doc = Parse(\"Operated by ::LEGAL_NAME::.\"); // [InlineData(\"x\")]")]
    public void P001_CodeStillFlagged(string line) =>
        Assert.Single(Run(new PlaceholderIdentifiers(), Added("src/Legal/Parser.cs", line)));

    // P003

    [Fact]
    public void P003_IsInfo_SinceDogfood2() => Assert.Equal(Severity.Info, new AssertNothingTests().Severity);

    // P005

    [Theory]
    [InlineData("src/Admin/Login.cs", "        Password = string.Empty;")]
    [InlineData("src/Admin/Login.cs", "        options.Password = configuration[\"Admin:Password\"];")]
    [InlineData("src/Db.cs", "var cs = builder.Password = pwdFromVault;")]
    public void P005_PasswordAssignmentInCode_NotFlagged(string path, string line) =>
        Assert.Empty(Run(new SecretsInDiff(), Added(path, line)));

    [Theory]
    [InlineData("src/Db.cs", "var cs = \"Server=db;User Id=app;Password=Hunter2Prod;\";")]
    [InlineData("src/Db.cs", "var cs = $@\"Server={host};Password=Hunter2Prod;\";")]
    [InlineData("appsettings.json", "\"Default\": \"Server=db;Password=Hunter2Prod;\"")]
    [InlineData(".env", "DB_PASSWORD=x;Password=Hunter2Prod")]
    [InlineData("deploy/setup.ini", "Password = Hunter2Prod")]
    public void P005_PasswordInStringOrConfig_Flagged(string path, string line) =>
        Assert.Single(Run(new SecretsInDiff(), Added(path, line)));

    [Fact]
    public void P005_OtherKindsInCode_StillFlaggedOutsideStrings() =>
        Assert.Single(Run(new SecretsInDiff(), Added("src/K.cs", "// https://admin:Hunter2Prod@db.internal/")));

    // P008

    [Theory]
    [InlineData("tests/Admin/AdminPasswordTests.cs", "src/Web/Admin/AdminPassword.cs")]
    [InlineData("src/cart.test.ts", "src/cart.ts")]
    [InlineData("tests/test_orders.py", "app/orders.py")]
    [InlineData("pkg/orders_test.go", "pkg/orders.go")]
    [InlineData("spec/order_spec.rb", "lib/order.rb")]
    public void P008_TestDeletedWithItsSubject_NotFlagged(string test, string subject) =>
        Assert.Empty(Run(new DeletedTests(), Removed(test), Removed(subject)));

    [Fact]
    public void P008_SubjectKept_Flagged() =>
        Assert.Single(Run(new DeletedTests(), Removed("tests/Admin/AdminPasswordTests.cs"), Added("src/Web/Admin/AdminPassword.cs", "class AdminPassword { }")));

    [Fact]
    public void P008_OtherCodeRemoved_Flagged() =>
        Assert.Single(Run(new DeletedTests(), Removed("tests/OrderServiceTests.cs"), Removed("src/Billing.cs")));

    // P009

    [Fact]
    public void P009_CatchInsideStringLiteral_NotFlagged() =>
        Assert.Empty(Run(new SwallowedExceptions(), Added("tests/UiTests.cs",
            "await page.EvaluateAsync(\"t => { try { localStorage.setItem('k', t); } catch(e){} }\", theme);")));

    [Fact]
    public void P009_TypedCatchWithComment_StillFlagged() =>
        Assert.Single(Run(new SwallowedExceptions(), Added("tests/UiTests.cs",
            "catch (PlaywrightException)",
            "{",
            "    // A settle timeout is not itself a violation.",
            "}")));

    // P010

    [Fact]
    public void P010_CentralPackageManagement_OneFindingOnPackageVersion()
    {
        var findings = Run(new NewDependencies(),
            Added("src/Web/Web.csproj", "<PackageReference Include=\"Markdig\" />"),
            Added("Directory.Packages.props", "<PackageVersion Include=\"Markdig\" Version=\"0.41.0\" />"),
            Added("src/Data/Data.csproj", "<PackageReference Include=\"markdig\" />"));

        var finding = Assert.Single(findings);
        Assert.Equal("Directory.Packages.props", finding.Path);
        Assert.Equal("New dependency: Markdig", finding.Message);
    }

    [Fact]
    public void P010_DifferentPackages_EachFlagged() =>
        Assert.Equal(2, Run(new NewDependencies(),
            Added("src/Web/Web.csproj", "<PackageReference Include=\"Markdig\" Version=\"0.41.0\" />", "<PackageReference Include=\"AWSSDK.S3\" Version=\"4.0.0\" />")).Count);

    [Fact]
    public void P010_SameNameInDifferentEcosystems_EachFlagged() =>
        Assert.Equal(2, Run(new NewDependencies(),
            Added("requirements.txt", "requests==2.32.0"),
            Added("package.json", "{", "  \"dependencies\": {", "    \"requests\": \"^1.0.0\"", "  }", "}")).Count);

    // P012

    [Theory]
    [InlineData("scripts/ci_test_annotations.py")]
    [InlineData("tools/report/summarize.py")]
    public void P012_PrintInScriptFolderPython_NotFlagged(string path) =>
        Assert.Empty(Run(new DebugLeftovers(), Added(path, "    print(f\"::error title={name}::{text}\")")));

    [Theory]
    [InlineData("app/orders.py", "    breakpoint()")]
    [InlineData("scripts/run.py", "    import pdb")]
    [InlineData("scripts/run.js", "console.log(x);")]
    public void P012_OtherDebugStatements_StillFlagged(string path, string line) =>
        Assert.Single(Run(new DebugLeftovers(), Added(path, line)));

    private static ChangedFile Removed(string path) => new(path, FileChangeStatus.Removed);
}
