// <auto-generated />
using System;
using Aibysitter.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aibysitter.Web.Data.Migrations
{
    [DbContext(typeof(AibysitterDbContext))]
    [Migration("20261002144724_InitialScoreHistory")]
    partial class InitialScoreHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aibysitter.Web.Data.ScoreHistoryEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("Repo")
                        .IsRequired()
                        .HasMaxLength(140)
                        .IsUnicode(false)
                        .HasColumnType("varchar(140)");

                    b.Property<short>("RulesetVersion")
                        .HasColumnType("smallint");

                    b.Property<byte>("Score")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Source")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("Repo", "FileName", "CreatedUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_ScoreHistory_Repo_File_Created");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Repo", "FileName", "CreatedUtc"), new[] { "RulesetVersion", "Score", "Grade" });

                    b.ToTable("ScoreHistory", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_ScoreHistory_FileName", "[FileName] IN ('CLAUDE.md', 'AGENTS.md', '.github/copilot-instructions.md', 'GEMINI.md', '.cursorrules', '.windsurfrules')");

                            t.HasCheckConstraint("CK_ScoreHistory_Grade", "[Grade] IN ('A', 'B', 'C', 'D', 'F')");

                            t.HasCheckConstraint("CK_ScoreHistory_Score", "[Score] BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_ScoreHistory_Source", "[Source] IN (1, 2)");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
